[unstable]
build-std = ["core", "compiler_builtins"]
#build-std-features = ["compiler-builtins-mem"]

[build]
target = "/home/knoldus/programming/os-in-rust/x86_64-os-in-rust.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
